[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"

authors = [
  { name="agouet", email="agouet@example.com" },
]

license = { file = "LICENSE" } 


readme = "README.md"
requires-python = ">=3.7"
[project.urls]
home-page = "https://github.com/agouet/ft_package" 